### ISSUE TITLE
Question: Why did you use the WebApi middleware instead building your completely own middleware?

### ISSUE THREAD

**Issue by Rookian** [damianh/Cedar.CommandHandling#34]
Why did you use the WebApi middleware instead building your completely own middleware?

**Comment by damianh** [comment]
Lazyiness mostly; been meaning to rip it out.  Will probably do that when porting to netstandard (or if someone else gets there with a PR first).

**Comment by Rookian** [comment]
Do you know if it is possible to reuse content negotiation when using your own pipeline? 

I also try to build something you built and I am not sure how much I need to program by myself when not sticking with WebApi. As far as I understand we should reuse a lot of middleware components. I don't want to recreate a lot of things that already exists (content negotiation, authentication, ...).

**Comment by damianh** [comment]
The conneg bit is initially why I leaned on a web framework. There is a balance between middleware-all-the-things vs framework. Conneg is one of those things where I feel it belongs in the latter. Middleware, imho, work on the HTTP message only.

It's been a year since I looked at this lib (we're using it in production and it 'just works'), I need to revisit my decisions.
